ALTER PROCEDURE [dbo].[GET_CONTENT_LIST]  
@PAG_NID AS bigint
AS    
BEGIN    
	
    
	SELECT DISTINCT	C.CON_NID ContentId,
					CT.COT_CDESCRIPTION ContentName, 
					C.CON_OSTATE ContentState,
					CT.COT_OUPGRADEABLE,
					UC.COM_NID Component,
					CAST(CO.COM_CVALUE AS VARCHAR(MAX)) ComponentHtml,
					COM_NCANT_VAR_TEXT ComponentCantVarText,
					COM_NCANT_VAR_IMAGE ComponentCantVarImage
					
	FROM TBL_CONTENT C
	INNER JOIN TBL_CONTENT_TYPE CT ON C.COT_NID = CT.COT_NID
	INNER JOIN TBL_RSECTION S ON C.SEC_NID = S.SEC_NID
	INNER JOIN TBL_TSECTION_PAGE SP ON S.SEC_NID = SP.SEC_NID
	INNER JOIN TBL_PAGE P ON SP.PAG_NID = P.PAG_NID
	left join TBL_UCOMPONENT_TBL_CONTENT_TYPE UC ON UC.COT_NID = CT.COT_NID 
	left join TBL_RCOMPONENT CO ON CO.COM_NID = UC.COM_NID

	WHERE P.PAG_NID = @PAG_NID
	AND CT.COT_OUPGRADEABLE = 1
    
END


go

USE [crediflo_webpag]
GO

/****** Object:  UserDefinedTableType [dbo].[VALUEFIELDTYPE]    Script Date: 12/06/2019 13:53:33 ******/
CREATE TYPE [dbo].[VARIABLE_COMPONENT] AS TABLE(
	[VAR_NAME] [varchar](max) NOT NULL,
	[VAR_CVALUE] [varchar](max) NULL
	
)
GO


USE [crediflo_webpag]
GO
/****** Object:  StoredProcedure [dbo].[SPR_INS_NEW_COMPONENT]    Script Date: 12/06/2019 11:55:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SPR_INS_NEW_COMPONENT]
@PNID_COMPONENTE BIGINT,
@PI_CDESCRIPTION VARCHAR(500),
@PI_LISTA_VARIABLE AS VARIABLE_COMPONENT READONLY,
@RESULT_SP AS VARCHAR(100) OUTPUT
AS
BEGIN
	begin try
		--DECLARE @PNID_COMPONENTE BIGINT
		--SET @PNID_COMPONENTE = 12

				declare @CANT_VAR_TEXT BIGINT, @CANT_VAR_IMAGE BIGINT, @CONT BIGINT, 
		@COMPONENT VARCHAR(MAX), @INDICE BIGINT, @NAME_COMPONENT VARCHAR(MAX), 
		@ID_COMPONENT BIGINT,@SQL VARCHAR(MAX),@NAME_VARIABLE VARCHAR(MAX),
		@ID_SECTION BIGINT, @ORDER BIGINT, @CONTENEDOR VARCHAR(MAX),
		@COMPONENT_LIST VARCHAR(MAX)

		SET @ID_SECTION = (SELECT SEC_NID 
			FROM TBL_CONTENT A INNER JOIN 
			TBL_CONTENT_TYPE B ON A.COT_NID = B.COT_NID INNER JOIN 
			TBL_UCOMPONENT_TBL_CONTENT_TYPE C ON B.COT_NID = C.COT_NID
		 WHERE COM_NID = @PNID_COMPONENTE
		)

		SET @COMPONENT = (SELECT CAST(COM_CVALUE AS VARCHAR(MAX)) FROM TBL_RCOMPONENT WHERE COM_NID = @PNID_COMPONENTE)
		SET @NAME_COMPONENT = (SELECT COM_CNAME FROM TBL_RCOMPONENT WHERE COM_NID = @PNID_COMPONENTE)
		--LIST
		SET @COMPONENT_LIST = (	
								CASE WHEN (
									SELECT COM_OWITH_LIST 
									FROM TBL_RCOMPONENT WHERE COM_NID = @PNID_COMPONENTE
								) = 1 THEN
									(
									SELECT CAST(COM_CVALUE AS VARCHAR(MAX)) 
									FROM TBL_RCOMPONENT WHERE COM_NPARENT_COMPONENT = @PNID_COMPONENTE
									)
								ELSE
									''
								END
								)
		

		SET @ID_COMPONENT = (SELECT COT_NID FROM TBL_RCOMPONENT C INNER JOIN TBL_UCOMPONENT_TBL_CONTENT_TYPE UC ON C.COM_NID = UC.COM_NID WHERE C.COM_NID = @PNID_COMPONENTE)
		--SET @CANT_VAR_TEXT = (SELECT COM_NCANT_VAR_TEXT FROM TBL_RCOMPONENT WHERE COM_NID = @PNID_COMPONENTE)
		--SET @CANT_VAR_IMAGE = (SELECT COM_NCANT_VAR_IMAGE FROM TBL_RCOMPONENT WHERE COM_NID = @PNID_COMPONENTE)
		SET @INDICE = (SELECT CHARINDEX('*variableImage',cast(@COMPONENT as varchar(max)))) 
		SET @CONT = 1
		SET @SQL = ''
		SET @CONTENEDOR = (SELECT CAST(COT_CISTYLE AS varchar(MAX)) 
		FROM TBL_UCOMPONENT_TBL_CONTENT_TYPE UCC INNER JOIN
		TBL_CONTENT_TYPE CT ON UCC.COT_NID = CT.COT_NID
		WHERE COM_NID = @PNID_COMPONENTE)
		

		SET @ORDER = (	select MAX(B1.CON_NORDER) + 1
						from TBL_CONTENT_TYPE a inner join 
						TBL_CONTENT b on a.cot_nid = b.cot_nid
						inner join TBL_CONTENT b1 on b1.CON_NID_PARENT = b.CON_NID
						where a.cot_nid = @ID_COMPONENT group by b1.CON_NID_PARENT)

		--print @ID_COMPONENT
		--print @ORDER

		if ((SELECT CHARINDEX('*contInt*',@NAME_COMPONENT)) > 0)
		begin
			set @NAME_COMPONENT = replace(@NAME_COMPONENT,'*contInt*',CAST(@ORDER AS VARCHAR(MAX)))
		end
		else
		begin
			set @NAME_COMPONENT = @NAME_COMPONENT  + '_' + CAST(@ORDER AS VARCHAR(MAX))
		end

		WHILE (@INDICE <> 0) --@CONT < @CANT_VAR_TEXT
		BEGIN
	
			SET @COMPONENT = REPLACE(@COMPONENT,'*variableImage' + CAST(@CONT AS VARCHAR(MAX)) + '*','[@IMAGE_' + @NAME_COMPONENT + CAST(@CONT AS VARCHAR(MAX)) + ']')
			SET @NAME_VARIABLE = 'IMAGE_' + @NAME_COMPONENT + CAST(@CONT AS VARCHAR(MAX))
	
			SET @SQL = @SQL + ' INSERT INTO TBL_RVARIABLE VALUES(''' + @NAME_VARIABLE + ''',''Ruta Imagen ' + @NAME_COMPONENT + CAST(@ORDER AS VARCHAR(MAX)) + ''','''',1,2,null,null,@ID_COT_NID) '
			
			SET @INDICE = (CHARINDEX('*variableImage',cast(@COMPONENT as varchar(max)))) 
			SET @CONT = @CONT + 1
	
			--PRINT @INDICE
			--PRINT @COMPONENT
			--PRINT @CONT
		END

		------

		SET @INDICE = (SELECT CHARINDEX('*variableText',cast(@COMPONENT as varchar(max)))) 
		set @CONT = 1

		WHILE (@INDICE <> 0) --@CONT < @CANT_VAR_TEXT
		BEGIN
	
			SET @COMPONENT = REPLACE(@COMPONENT,'*variableText' + CAST(@CONT AS VARCHAR(MAX)) + '*','[@TEXT_' + @NAME_COMPONENT + CAST(@CONT AS VARCHAR(MAX)) + ']')
			SET @NAME_VARIABLE = 'TEXT_' + @NAME_COMPONENT + CAST(@CONT AS VARCHAR(MAX))
	
			SET @SQL = @SQL + ' INSERT INTO TBL_RVARIABLE VALUES(''' + @NAME_VARIABLE + ''',''Texto ' + @NAME_COMPONENT + CAST(@ORDER AS VARCHAR(MAX)) + ''','''',1,1,null,null,@ID_COT_NID) '

			SET @INDICE = (CHARINDEX('*variableText',cast(@COMPONENT as varchar(max)))) 
			SET @CONT = @CONT + 1
	
			--PRINT @INDICE
			--PRINT @COMPONENT
			--PRINT @CONT
		END

		

		--PRINT @ID_COMPONENT
		--PRINT @SQL
		--PRINT @ORDER
		--PRINT @NAME_COMPONENT
		--PRINT @CONT
		--PRINT @COMPONENT
		print @NAME_COMPONENT
		print CHARINDEX('*contInt*',@NAME_COMPONENT)
		print replace(@NAME_COMPONENT,'*contInt*',CAST(@ORDER AS VARCHAR(MAX)))

		--if ( (SELECT CHARINDEX('*contInt*',@NAME_COMPONENT)) > 0)
		--begin
		--print 'xxxx'

			set @COMPONENT = replace(CAST(@COMPONENT AS VARCHAR(MAX)) ,'*consecutivo*',CAST(@ORDER AS VARCHAR(MAX)))


			SET @SQL =  ' DECLARE @ID_COT_NID BIGINT ' +
			' INSERT INTO TBL_CONTENT_TYPE VALUES(''' + @NAME_COMPONENT + ''','''', ''' + CAST(@COMPONENT AS VARCHAR(MAX)) + ''',1,1) ' +
			' SET @ID_COT_NID = SCOPE_IDENTITY() ' +
			' INSERT INTO TBL_CONTENT VALUES(''' + @NAME_COMPONENT + ''','''', ' +  CAST(@ORDER AS VARCHAR(MAX)) + ',1,' + 
			CAST(@ID_COMPONENT AS VARCHAR(MAX)) + ', @ID_COT_NID ,' + 
			CAST(@ID_SECTION AS VARCHAR(MAX))+ ')' + ' ' + @SQL

			SET @CONTENEDOR = REPLACE(@CONTENEDOR,'<!--New Object-->',
			'[?' + @NAME_COMPONENT + '] 
			<!--New Object--> '
			)


		--	print @CONTENEDOR
		--end
		--else
		--begin
		--	SET @SQL =  ' DECLARE @ID_COT_NID BIGINT ' +
		--	' INSERT INTO TBL_CONTENT_TYPE VALUES(''' + @NAME_COMPONENT + '_' + CAST(@ORDER AS VARCHAR(MAX)) + ''','''', ''' + CAST(@COMPONENT AS VARCHAR(MAX)) + ''',1,1) ' +
		--	' SET @ID_COT_NID = SCOPE_IDENTITY() ' +
		--	' INSERT INTO TBL_CONTENT VALUES(''' + @NAME_COMPONENT  + '_' + CAST(@ORDER AS VARCHAR(MAX)) +  ''','''', ' +  CAST(@ORDER AS VARCHAR(MAX)) + ',1,' + 
		--	CAST(@ID_COMPONENT AS VARCHAR(MAX)) + ', @ID_COT_NID ,' + 
		--	CAST(@ID_SECTION AS VARCHAR(MAX))+ ')' + ' ' + @SQL

		--	SET @CONTENEDOR = REPLACE(@CONTENEDOR,'<!--New Object-->',
		--	'[?' + @NAME_COMPONENT + '_' + CAST(@ORDER AS VARCHAR(MAX)) + '] 
		--	<!--New Object--> '
		--	)
			
		--	print @CONTENEDOR
		--end

		IF(LEN(@COMPONENT_LIST) > 0)
		BEGIN

			SET @NAME_COMPONENT = (SELECT COM_CNAME FROM TBL_RCOMPONENT WHERE COM_NPARENT_COMPONENT = @PNID_COMPONENTE)
			SET @CONT = (select ((COUNT(B1.CON_NORDER) + 2)  / 4) + 1
						from TBL_CONTENT_TYPE a inner join 
						TBL_CONTENT b on a.cot_nid = b.cot_nid
						inner join TBL_CONTENT b1 on b1.CON_NID_PARENT = b.CON_NID
						where a.cot_nid = @ID_COMPONENT group by b1.CON_NID_PARENT)

						PRINT @CONT
			SET @COMPONENT_LIST = REPLACE(@COMPONENT_LIST,'*consecutivo*',CAST(@CONT AS VARCHAR(MAX)))

			--SET @SQL = @SQL + ' SET @LIST = ''' + @COMPONENT_LIST + ''' '

			SET @SQL = @SQL + ' INSERT INTO TBL_CONTENT_TYPE VALUES(''' + @NAME_COMPONENT + '' + CAST(@ORDER AS VARCHAR(MAX)) + ''','''', ''' + CAST(@COMPONENT_LIST AS VARCHAR(MAX)) + ''',1,1) ' +
			' SET @ID_COT_NID = SCOPE_IDENTITY() ' +
			' INSERT INTO TBL_CONTENT VALUES(''' + @NAME_COMPONENT  + '' + CAST(@ORDER AS VARCHAR(MAX)) +  ''','''', ' +  CAST(@ORDER AS VARCHAR(MAX)) + ',1,' + 
			CAST(@ID_COMPONENT AS VARCHAR(MAX)) + ', @ID_COT_NID ,' + 
			CAST(@ID_SECTION AS VARCHAR(MAX))+ ') ' 

			SET @CONTENEDOR = REPLACE(@CONTENEDOR,'<!--New ObjectList-->',
			'[?' + @NAME_COMPONENT + '' + CAST(@ORDER AS VARCHAR(MAX)) + '] 
			<!--New ObjectList--> '
			)
		END

		--PRINT '1'
		--PRINT @SQL
		--PRINT '1'
		
		SET @SQL = @SQL + 
		' UPDATE TBL_CONTENT_TYPE SET COT_CISTYLE = ''' + @CONTENEDOR + ''' WHERE COT_NID = ' + CAST(@ID_COMPONENT AS VARCHAR(MAX))

		--SET @ORDER = (	select *--count(B1.CON_NORDER) + 1
		--		from TBL_CONTENT_TYPE a inner join 
		--		TBL_CONTENT b on a.cot_nid = b.cot_nid
		--		inner join TBL_CONTENT b1 on b1.CON_NID_PARENT = b.CON_NID
		--		where a.cot_nid = 5 group by b1.CON_NID_PARENT)



		PRINT @SQL

		EXEC(@SQL)

		RETURN 1
	END TRY
	BEGIN CATCH
		
		SET @RESULT_SP = 'Error: No fue posible actualizar el registro, por favor valide.'
		RETURN 0
	END CATCH  


END

GO
